import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <header className='flex justify-between px-28 py-4 bg-green-100 text-lg'>
            <Link className='font-bold' href='/'>Blog</Link>
            <Link className='hover:text-green-400' href='/write'>게시글 작성</Link>
        </header>
        {children}
        </body>
        </html>
    );
}
